site_name: Anthos Workshop
nav:

- 'Platform' : 'platform'
- 'Security' : 'security'
- 'Developer' : 'develop'
- 'Operator' : 'operate'

- Platforms: 
  - 'Overview'  : 'platform/index.md'
  - 'Clusters'  : 'platform/clusters.md'
  - 'Config'    : 'platform/config.md'
  - 'Mesh'      : 'platform/mesh.md'
  - 'Pipeline'  : 'platform/pipeline.md'

- Security:
  - 'Overview' : 'security/index.md'

- Developer:
  - 'Overview' : 'develop/index.md'

- Operator:
  - 'Overview' : 'operate/index.md'



#-------------
markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed

theme:
  name: 'material'
  features:
    - tabs
  logo: images/logo.svg
  favicon: images/favicon.png